theme: jekyll-theme-midnight
title: InfoGraviton
description: journal club on aspects of information, quantum theory, and gravity
github:
  is_project_page: false
future: true
timezone: America/Sao_Paulo

collections:
  seminars:
    output: true
  suggestions:
    output: false
  bibliography:
    output: false
    
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "seminars"
    values:
      layout: "seminar"
